# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b1682bb83b24a445238da68c292cd246193c57525418b568fff782f5e8ab91a59717250dc20cdefae49b009691a23ba88c62c81160f52276f0207a6ad9bb0b1

test:
  secret_key_base: b04111a09e2a87fe356b18986f539e8265e8e8c5efe1a26f39d6533dc546b2a23c675bec6133a3bcd5027708c7106a4c4586e0b06770459273ee3c579bfc9cf1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
